INSERT INTO ATORES (ID, PRIMEIRO_NOME, ULTIMO_NOME, GENERO)
VALUES (1, 'JAMES', 'STWART', 'M');
INSERT INTO ATORES (ID, PRIMEIRO_NOME, ULTIMO_NOME, GENERO)
VALUES (2, 'PETER', 'OTOOLE', 'M');
INSERT INTO ATORES (ID, PRIMEIRO_NOME, ULTIMO_NOME, GENERO)
VALUES (3, 'ROBERT', 'DENIRO', 'M');
INSERT INTO ATORES (ID, PRIMEIRO_NOME, ULTIMO_NOME, GENERO)
VALUES (4, 'HARRISON', 'FORD', 'M');
INSERT INTO ATORES (ID, PRIMEIRO_NOME, ULTIMO_NOME, GENERO)
VALUES (5, 'STEPHEN', 'BALDWIN', 'M');
INSERT INTO ATORES (ID, PRIMEIRO_NOME, ULTIMO_NOME, GENERO)
VALUES (6, 'PETER', 'OTOOLE', 'M');
INSERT INTO ATORES (ID, PRIMEIRO_NOME, ULTIMO_NOME, GENERO)
VALUES (7, 'MICHAEL', 'J. FOX', 'M');

SELECT * FROM ATORES;