INSERT INTO FILMES(ID, NOME, ANO, DURACAO)
VALUES(1, 'DE VOLTA PARA O FUTURO', 1986, 116);
INSERT INTO FILMES(ID, NOME, ANO, DURACAO)
VALUES(2, 'OS SETE SAMURAIS', 1954, 207);
INSERT INTO FILMES(ID, NOME, ANO, DURACAO)
VALUES(3, 'LAWRENCE DA ARÁBIA', 1962, 216);
INSERT INTO FILMES(ID, NOME, ANO, DURACAO)
VALUES(4, 'AMARGO PESADELO', 1972, 109);
INSERT INTO FILMES(ID, NOME, ANO, DURACAO)
VALUES(5, 'BLADE RUNNER', 1982, 117);
INSERT INTO FILMES(ID, NOME, ANO, DURACAO)
VALUES(6, 'DONNIE DARKO', 2001, 113);
INSERT INTO FILMES(ID, NOME, ANO, DURACAO)
VALUES(7, 'A VIAGEM DE CHIHIRO', 2001, 125);

SELECT * FROM FILMES;
