CREATE TABLE ELENCO_FILMES(
	ID NUMERIC PRIMARY KEY,
	ID_ATOR NUMERIC FOREIGN KEY REFERENCES ATORES(ID),
	ID_FILME NUMERIC FOREIGN KEY REFERENCES FILMES(ID),
	PAPEL VARCHAR(30) NOT NULL
);

SELECT * FROM ELENCO_FILMES;